[tool.poetry]
name = "agent"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Orca <testapp@copilotkit.ai>"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
copilotkit = "0.1.45"
tavily-python = "^0.5.1"
uvicorn = "^0.34.0"
dotenv = "^0.9.9"
langchain = ">=0.1.0"
langchain-core = ">=0.1.5"
langchain-community = ">=0.0.1"
langchain-experimental = ">=0.0.11"
langchain-openai = ">=0.0.1"
langgraph = "^0.3.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
langgraph_server = "langgraph_server:main"